version: '3'

services:
  app:
    image: openjdk:8-alpine
    working_dir: /home/app
    volumes:
      - "./target/:/home/app"
    command: java -jar test-0.0.1-jar-with-dependencies.jar
    environment:
      USER: andersori
